2025-03-17 07:16:52 - ERROR - api:459 - Error rendering index page: type object 'DevConfig' has no attribute 'VERSION'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 442, in index
    "version": config.VERSION,
AttributeError: type object 'DevConfig' has no attribute 'VERSION'
2025-03-17 07:16:52 - ERROR - api:34 - Error in index: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 442, in index
    "version": config.VERSION,
AttributeError: type object 'DevConfig' has no attribute 'VERSION'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 460, in index
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 07:17:12 - ERROR - api:459 - Error rendering index page: type object 'DevConfig' has no attribute 'VERSION'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 442, in index
    "version": config.VERSION,
AttributeError: type object 'DevConfig' has no attribute 'VERSION'
2025-03-17 07:17:12 - ERROR - api:34 - Error in index: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 442, in index
    "version": config.VERSION,
AttributeError: type object 'DevConfig' has no attribute 'VERSION'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 460, in index
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 07:28:04 - ERROR - api:459 - Error rendering index page: type object 'SmartcardManager' has no attribute 'get_reader_count'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 443, in index
    "readers_available": await SmartcardManager.get_reader_count(),
AttributeError: type object 'SmartcardManager' has no attribute 'get_reader_count'
2025-03-17 07:28:04 - ERROR - api:34 - Error in index: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 443, in index
    "readers_available": await SmartcardManager.get_reader_count(),
AttributeError: type object 'SmartcardManager' has no attribute 'get_reader_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 460, in index
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 07:32:19 - ERROR - api:571 - Error rendering NFC page: type object 'NFCManager' has no attribute 'is_available'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 533, in nfc
    nfc_available = NFCManager.is_available()
AttributeError: type object 'NFCManager' has no attribute 'is_available'
2025-03-17 07:32:19 - ERROR - api:34 - Error in nfc: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 533, in nfc
    nfc_available = NFCManager.is_available()
AttributeError: type object 'NFCManager' has no attribute 'is_available'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 572, in nfc
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 07:32:24 - ERROR - api:627 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 586, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 07:32:24 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 586, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 628, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 07:32:59 - ERROR - api:571 - Error rendering NFC page: type object 'NFCManager' has no attribute 'is_available'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 533, in nfc
    nfc_available = NFCManager.is_available()
AttributeError: type object 'NFCManager' has no attribute 'is_available'
2025-03-17 07:32:59 - ERROR - api:34 - Error in nfc: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 533, in nfc
    nfc_available = NFCManager.is_available()
AttributeError: type object 'NFCManager' has no attribute 'is_available'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 572, in nfc
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 07:46:49 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 07:46:49 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 07:55:18 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 07:55:18 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 08:10:48 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 08:10:48 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 08:40:44 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 08:40:44 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 08:41:57 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 08:41:57 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 08:56:27 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 08:56:27 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 09:11:23 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 09:11:23 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 09:18:56 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 09:18:56 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 09:27:38 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 09:27:38 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 09:52:44 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 09:52:44 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 10:22:49 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 10:22:49 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 10:41:09 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 10:41:09 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 10:42:50 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 10:42:50 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 10:42:53 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 10:42:53 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 10:49:09 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 10:49:09 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 10:51:57 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'
2025-03-17 10:51:57 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 561, in settings
    "simulation_mode": config.SIMULATION_MODE
AttributeError: type object 'DevConfig' has no attribute 'SIMULATION_MODE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
2025-03-17 11:02:23 - ERROR - api:602 - Error rendering settings page: type object 'DevConfig' has no attribute 'BASE_DIR'
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 585, in settings
    plugin_dir = Path(config.BASE_DIR) / "plugins"
AttributeError: type object 'DevConfig' has no attribute 'BASE_DIR'. Did you mean: 'DATA_DIR'?
2025-03-17 11:02:23 - ERROR - api:34 - Error in settings: 500: Error rendering page
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 585, in settings
    plugin_dir = Path(config.BASE_DIR) / "plugins"
AttributeError: type object 'DevConfig' has no attribute 'BASE_DIR'. Did you mean: 'DATA_DIR'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\routes.py", line 32, in wrapper
    return await func(*args, **kwargs)
  File "K:\anita\poc\backend\routes\routes.py", line 603, in settings
    raise HTTPException(status_code=500, detail="Error rendering page")
fastapi.exceptions.HTTPException: 500: Error rendering page
